"""API package for Attendance Recovery Agent."""
from .attendance_api import (
    get_student,
    get_all_students,
    get_all_subjects,
    get_subject,
    get_raw_attendance_summary,
    get_raw_subject_attendance,
    get_attendance_history,
    record_period_attendance,
    get_timetable,
    get_upcoming_classes,
    get_leave_records,
    apply_leave,
    save_attendance_event,
    get_attendance_memory,
    get_subject_memory,
    save_notification,
    get_notifications,
    mark_notification_as_read,
    search_attendance_policy,
)

__all__ = [
    "get_student",
    "get_all_students",
    "get_all_subjects",
    "get_subject",
    "get_raw_attendance_summary",
    "get_raw_subject_attendance",
    "get_attendance_history",
    "record_period_attendance",
    "get_timetable",
    "get_upcoming_classes",
    "get_leave_records",
    "apply_leave",
    "save_attendance_event",
    "get_attendance_memory",
    "get_subject_memory",
    "save_notification",
    "get_notifications",
    "mark_notification_as_read",
    "search_attendance_policy",
]
